import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'getting-started/index' },
      items: [
        'getting-started/setting-up-user-account',
        'getting-started/managing-api-tokens',
        'getting-started/publishing-a-module',
        'getting-started/managing-subscription'
      ],
    },
    {
      type: 'category',
      label: 'Module',
      link: { type: 'doc', id: 'module/index' },
      items: [
        'module/publication',
        'module/usage',
      ],
    },
    'subscriptions',
    {
      type: 'category',
      label: 'CLI',
      link: { type: 'doc', id: 'cli/index' },
      items: [
        'cli/login',
        'cli/logout',
        'cli/module/list',
        'cli/module/publish'
      ],
    },
    {
      type: 'category',
      label: 'CI Integrations',
      link: { type: 'doc', id: 'ci/index' },
      items: [
        'ci/github-actions'
      ],
    },
  ]
};

export default sidebars;
