import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/setting-up-user-account',
        'getting-started/managing-user-tokens',
        'getting-started/managing-subscription'
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/publishing-a-package',
      ],
    },
    {
      type: 'category',
      label: 'CI Integrations',
      items: ['ci/github-actions'],
    },
  ]
};

export default sidebars;
